### ISSUE TITLE
traceback with activerecord 5.2.0

### ISSUE THREAD

**Issue by stan3** [artemave/REST-assured#13]
Seeing this with current latest activerecord

```
$ bundle exec rest-assured :memory:
Traceback (most recent call last):
	12: from /var/tmp/bundle/bin/rest-assured:23:in `<main>'
	11: from /var/tmp/bundle/bin/rest-assured:23:in `load'
	10: from /var/tmp/bundle/gems/rest-assured-3.0.1/bin/rest-assured:73:in `<top (required)>'
	 9: from /var/tmp/bundle/gems/rest-assured-3.0.1/bin/rest-assured:73:in `require'
	 8: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/application.rb:13:in `<top (required)>'
	 7: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/application.rb:14:in `<module:RestAssured>'
	 6: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/application.rb:16:in `<class:Application>'
	 5: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/application.rb:16:in `include'
	 4: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/config.rb:44:in `included'
	 3: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/config.rb:71:in `setup_db'
	 2: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/config.rb:113:in `migrate_db'
	 1: from /var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/config.rb:108:in `block in migrate_db'
/var/tmp/bundle/gems/rest-assured-3.0.1/lib/rest-assured/config.rb:104:in `block in migrate_db': undefined method `migrate' for ActiveRecord::Migrator:Class (NoMethodError)

```

**Comment by artemave** [comment]
AR5: works, AR5.2: broken? Not much of a semantic versioning, is it?

Anyway, will fix at some point. Feel free to fix & pr to have it sooner :)
