### ISSUE TITLE
Trouble trying to use mysql2 

### ISSUE THREAD

**Issue by cookiescrumbs** [artemave/REST-assured#4]
I'm trying to use REST-assured with mysql2. 
However, I'm getting the following error: 

```
/usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
	from /usr/local/bundle/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:50:in `establish_connection'
	from /usr/local/bundle/gems/rest-assured-2.0.1/lib/rest-assured/config.rb:101:in `connect_db'
	from /usr/local/bundle/gems/rest-assured-2.0.1/lib/rest-assured/config.rb:71:in `setup_db'
	from /usr/local/bundle/gems/rest-assured-2.0.1/lib/rest-assured/config.rb:46:in `included'
	from /usr/local/bundle/gems/rest-assured-2.0.1/lib/rest-assured/application.rb:16:in `include'
	from /usr/local/bundle/gems/rest-assured-2.0.1/lib/rest-assured/application.rb:16:in `<class:Application>'
	from /usr/local/bundle/gems/rest-assured-2.0.1/lib/rest-assured/application.rb:14:in `<module:RestAssured>'
	from /usr/local/bundle/gems/rest-assured-2.0.1/lib/rest-assured/application.rb:13:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from bin/rest-assured:73:in `<main>'
```

I have the gem installed. Any  ideas? cheers

**Comment by cookiescrumbs** [comment]
```gem install mysql2 -v 0.3.18``` fixed it.

**Comment by cookiescrumbs** [comment]
Found the solution here https://github.com/brianmario/mysql2/issues/675

**Comment by artemave** [comment]
Glad you found a workaround.
